services:
  traefik:
    image: traefik:v2.11
    container_name: ducked-traefik
    command:
      - "--log.level=INFO"
      - "--providers.docker=true"
      - "--providers.docker.network=ducked-net"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      # Global HTTP -> HTTPS Redirect
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      # Let's Encrypt Resolver
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.email=${ACME_EMAIL:-admin@ducked.dev}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      - "--api.dashboard=true"
      - "--api.insecure=true"
    ports:
      - "80:80"       # HTTP (Redirects to HTTPS)
      - "443:443"     # HTTPS
      - "8088:8080"   # Traefik dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt
    networks:
      - ducked-net
    restart: unless-stopped

networks:
  ducked-net:
    name: ducked-net
    driver: bridge
